services:
  my_mysql:
    image: mysql:8
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: nouveau_mot_de_passe
      MYSQL_DATABASE: location_voiture
      
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: my_mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app_network

  my_app:
    image: php:7.4-fpm
    container_name: my_app
    volumes:
      - ./your-app:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
